services:
  weatherforecast.dataingestion:
    image: quangtran2/weatherforecastdataingestion:latest

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  weatherforecast.databaseapi:
    image: quangtran2/weatherforecastdatabaseapi:latest
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
  logs:

networks:
  weathernet:
    driver: bridge
