services:
  weatherforecast.dataingestion:
    image: quangtran2/weatherforecastdataingestion:latest
    networks:
      - weathernet

  weatherforecast.databaseapi:
    image: quangtran2/weatherforecastdatabaseapi:latest
    volumes:
      - ./logs:/app/logs
    networks:
      - weathernet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - weathernet

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - weathernet

  kafka-ui:
    image: provectuslabs/kafka-ui:latest    
    networks:
      - weathernet

  debezium:
    image: debezium/connect:2.5
    networks:
      - weathernet

  # debezium-ui:
  #   image: debezium/debezium-ui:latest
  #   networks:
  #     - weathernet

  debezium-connector-config:
    image: curlimages/curl
    networks:
      - weathernet    

  weatherforecast.dataanalysis:
    image: quangtran2/weatherforecastdataanalysis:latest
    networks:
      - weathernet

  weatherforecast.dataanalysis.worker:
    image: quangtran2/weatherforecastdataanalysis:latest
    networks:
      - weathernet

  weatherforecast.dataanalysis.beat:
    image: quangtran2/weatherforecastdataanalysis:latest
    networks:
      - weathernet

volumes:
  logs:
  zookeeper_data:
  zookeeper_log:
  kafka_data:

networks:
  weathernet:
    driver: bridge
