services:
  weatherforecast.databaseapi:
    image: weatherforecastdatabaseapi:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WeatherForecast.DatabaseApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Projects\WeatherForecast\src\WeatherForecastKPDL\Services\DatabaseApi\WeatherForecast.DatabaseApi:/app:rw
      - C:\Projects\WeatherForecast\src\WeatherForecastKPDL:/src:rw
      - C:\Users\quang\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\quang\.nuget\packages:/.nuget/packages:ro
      - C:\Users\quang\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\quang\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\quang\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\quang\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/WeatherForecast.DatabaseApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  weatherforecast.dataingestion:
    image: weatherforecastdataingestion:dev
    build:
      args:
        LAUNCHING_FROM_VS: true
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WeatherForecast.DataIngestion"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Projects\WeatherForecast\src\WeatherForecastKPDL\Services\DataIngestion\WeatherForecast.DataIngestion:/app:rw
      - C:\Projects\WeatherForecast\src\WeatherForecastKPDL:/src:rw
      - C:\Users\quang\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\quang\.nuget\packages:/.nuget/packages:ro
      - C:\Users\quang\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\quang\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\quang\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\quang\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/WeatherForecast.DataIngestion.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
